jsnaughty/deobfuscate/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'deobfuscate'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.get_js, name='get_js'),
    url(r'^about/$', views.about, name='about'),
    url(r'^team/$', views.team, name='team'),
    url(r'^results/$', views.results, name='results'),
    url(r'^get_js/$', views.get_js, name='get_js'),
    url(r'minify/$', views.minify, name='minify'),
]

jsnaughty/jsnaughty/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    #url(r'^$', RedirectView.as_view(url = reverse_lazy('/deobfuscate'), permanent=False)),
    url(r'^', include('deobfuscate.urls')),
    url(r'^deobfuscate/', include('deobfuscate.urls')),
    url(r'^admin/', admin.site.urls),
]

jsnaughty/deobfuscate/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class PlaceHolderModel(models.Model):
    ph_text = models.CharField(max_length=200)
      
    def __str__(self):
        return self.ph_text

jsnaughty/deobfuscate/forms.py
from django import forms
from django.core.validators import MaxLengthValidator
#from django.utils.safestring import mark_safe
#from crispy_forms.helper import FormHelper
#from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit


#From http://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms
#class HorizontalRadioRenderer(forms.RadioSelect.renderer):
#    def render(self):
#        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

EXAMPLES = (
    ("EX1", 'Example 1'),
)

EX_TEXT = open("deobfuscate/web_examples/paper_ex.min.js", 'r').read()

class JSForm(forms.Form):
    #in_text = forms.Textarea(label = "Obfuscated Text")
    #in_text = forms.CharField(widget=forms.Textarea)
    in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea'}), initial=EX_TEXT, label = "", validators=[MaxLengthValidator(10000)])
    #in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea', 'placeholder' : 'Enter your Javascript Here.'}), label = "", validators=[MaxLengthValidator(10000)])
    mix_jsnice = forms.ChoiceField(widget=forms.RadioSelect, label = "<a href=\"http://jsnice.org\">JSNice Mixing</a>", choices =(('Y', 'Enable (Best Results)'), ('N', 'Disable')), initial='Y')
    #mix_jsnice = forms.ChoiceField(widget=forms.RadioSelect(renderer=HorizontalRadioRenderer), label = "JSNice Mixing", choices =(('Y', 'Enable (Best Results)'), ('N', 'Disable')), initial='Y')

#    def __init__(self, *args, **kwargs):
#        self.helper = FormHelper()
#        self.helper.layout = Layout(
#            ButtonHolder(
#                Submit('submit', 'Submit', css_class='button white')
#            )
#        )
#        super(JSForm, self).__init__(*args, **kwargs)

class JSMinForm(forms.Form):
    in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea', 'placeholder' : 'Enter your Javascript here.'}), label = "", validators=[MaxLengthValidator(10000)])

class JSMinErrorForm(forms.Form):
    in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea'}), initial = "(Error) Minifier failed.  Make sure your Javascript is valid.", label = "", validators=[MaxLengthValidator(10000)])


class LastJSInvalidForm(forms.Form):
    '''
    Used as alternate form for when the past Javascript entered failed
    the pre or post processing.
    '''
    in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea'}), initial='(Error) Please enter valid javascript.', label = "", validators=[MaxLengthValidator(10000)])
    mix_jsnice = forms.ChoiceField(widget=forms.RadioSelect, label = "<a href=\"http://jsnice.org\">JSNice Mixing</a>", choices =(('Y', 'Enable (Best Results)'), ('N', 'Disable')), initial='Y')
    
class ServerErrorForm(forms.Form):
    '''
    Used as alternate form for when the moses server is offline or 
    otherwise failed.
    '''
    in_text = forms.CharField(widget=forms.Textarea(attrs={'class' : 'inline-txtarea'}), initial='(Error) Sorry, internal server is either offline or not functioning.', label = "", validators=[MaxLengthValidator(10000)])
    mix_jsnice = forms.ChoiceField(widget=forms.RadioSelect, label = "<a href=\"http://jsnice.org\">JSNice Mixing</a>", choices =(('Y', 'Enable (Best Results)'), ('N', 'Disable')), initial='Y')

jsnaughty/deobfuscate/views.py
import time
from random import randint
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.template import Context

from .forms import JSForm, JSMinForm, JSMinErrorForm, ServerErrorForm, LastJSInvalidForm
from .models import PlaceHolderModel
#from deobfuscate.internal_test import MockClient
from deobfuscate.experiments import MosesClient
from deobfuscate.tools import Uglifier

# Create your views here.
class IndexView(generic.ListView):
    #Display an about and link the actual text?
    template_name = 'deobfuscate/index.html'
    #context_object_name = 'javascript_deofuscation'
    def get_queryset(self):
        return JSForm()
    
def phraseTables(request):
    return render(request, "deobfuscate/downloads.html")
    
def about(request):
    #output = "Behold, The Deobfuscated Javascript!"
    return render(request, 'deobfuscate/about.html')
    
def team(request):
    #output = "Behold, The Deobfuscated Javascript!"
    return render(request, 'deobfuscate/team.html')

def minify(request):
    if request.method == 'POST':
        print("Minifying")
        # create a form instance and populate it with data from the request:
        form = JSMinForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            normal_text = form.cleaned_data['in_text']
            uglify = Uglifier(flags=["-m"])
            #if(True):
            try:
                (ok, minified, msg) = uglify.web_run_end(normal_text)
                #print(minified)
                if(minified == ""):
                    raise ValueError
                return render(request, 'deobfuscate/minify.html', {'form': form,'out_text': minified, 'height' : minified.count("\n") + 1, 'width' : 80})

            except:
                print("Min fail.")
                form = JSMinErrorForm()
                return render(request, "deobfuscate/minify.html", {'form': form, 'out_text': "", 'height' : 8})
        else:
            print("Min valid fail.")
            form = JSMinErrorForm()
            return render(request, "deobfuscate/minify.html", {'form': form, 'out_text': "", 'height' : 8})
    else:
        form = JSMinForm()
    
    return render(request, "deobfuscate/minify.html", {'form': form, 'out_text': "", 'height' : 8})     
    
def results(request, output):
    #output = "Behold, The Deobfuscated Javascript!"
    return render(request, 'deobfuscate/results.html', Context({'out_text': output}))
        
def get_js(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = JSForm(request.POST)
        # check whether it's valid:
        if form.is_valid(): #(For performance, we don't want to rerun the beautifiers I think)
            # process the data in form.cleaned_data as required
            #View testing.
            #return render(request, 'deobfuscate/get_js.html', Context({'form': form, 'out_text': "Pull the lever!"}))
            rClient = MosesClient("./tmp/")
            #try:
            start = time.time()
            #TODO: 0 must be replaced with a proper number (random? sequence? -> shouldn't overlap 
            #for things near the same time...  But is it actually an issue?)
            #Yes, used for the JSNICE temp file.  That will be overwritten on
            #high loads before being called...  Talk to Bogdan about what is best solution.
            #What else should we time -> JSNICE time + Hash time, I think.
            if(form.cleaned_data['mix_jsnice'] == 'Y'):
                mix = True
            else:
                mix = False
            
            #Pick a number to give an id for where we are saving the JSNICE temp file if necessary
            transaction_id = randint(1, 1000000000)
            annotated_output = rClient.deobfuscateJS(form.cleaned_data['in_text'], mix, transaction_id, False) #Validate here.
            #Annotated output includes performance metrics.  We'll control how they are output here.
            #For now, just output deobsfucation + jsnice error string if necessary
            output = annotated_output[1] + annotated_output[0]
            
            end = time.time()
            duration = end-start
            if(output in rClient.getValidationErrors()):
                form = LastJSInvalidForm()
                return render(request, "deobfuscate/get_js.html", {'form': form})
            elif(output == rClient.getServerError()):
                form = ServerErrorForm()
                #TODO: This should send an email alert to us that something has gone wrong.
                return render(request, "deobfuscate/get_js.html", {'form': form})
            else:
                # redirect to a new URL:
                #Context is giving an error for some reason.
                return render(request, 'deobfuscate/get_js.html', {'form': form,'out_text': output, 'height' : output.count("\n") + 1, 'width' : 80})
#                return render(request, 'deobfuscate/get_js.html', Context({'form': form,'out_text': "Total Process Time: " + str(duration) + "\n" + output, 'height' : output.count("\n") + 1, 'width' : 80}))
                #return render(request, 'deobfuscate/results.html', Context({'out_text': "Total Process Time: " + str(duration) + "\n" + output, 'height' : output.count("\n") + 1, 'width' : 80}))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = JSForm()
    #Replace with the form again.
    return render(request, "deobfuscate/get_js.html", {'form': form, 'out_text': "", 'height' : 8})

jsnaughty/deobfuscate/templates/deobfuscate/about.html
{% extends "deobfuscate/new_base.html" %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
<h1>About JSNaughty</h1>
<p>
JSNaughty is a tool for recovering names from obfuscated Javascript files.  It is based on 
framing the deobfuscation problem as a language translation problem - we translate the 
obfuscated names to meaningful names using the context in which variables are defined.
</p>
<p>
To do this, the tool makes uses of the <a href="http://www.statmt.org/moses/">Moses</a> 
statistical machine translation framework to perform the translation, along with some pre 
and post processing to handle differences between code and natural language - such as code's 
requirement for consistency within scope.
</p>
<p>
The source code for the tool can be found at on our GitHub page <a href="https://github.com/bvasiles/jsNaughty">here</a>.  In addition to the website, a more flexible environment to run
the tool can be found on <a href="https://hub.docker.com/r/caseycas/jsnaughty-moses/">DockerHub</a>, with addition instructions on running the docker container and the tool inside are 
in the README file <a href="https://github.com/bvasiles/jsNaughty/tree/master/DockerFolder">here</a>.
</p>
<h2>Using this website:</h2>
<p>
The <a href="{% url 'deobfuscate:get_js' %}">Home</a> page allows the recovering of obfuscated names from the UglifyJS obfuscation tool.  You can paste the Javascript obfuscated with this tool in the left text
box (replacing the example), and the tool will produced renamed (and indented if needed) Javascript.  If you included the JSNice mixing option then the tool combines the names suggested by Moses with names
suggested by JSNice.  Our experiements show this is the most effective option.  You can disable including the JSNice names by turning it off, or follow the link to try the renaming with just the JSNice tools.
</p>
<p>
Also, since our tool was designed to recover code minified by UglifyJS, we have included a web front end to minify Javascript with this tool <a href="{% url 'deobfuscate:minify' %}">here.</a>
</p>

    </div>
  </div>
</div>





{% endblock %}

jsnaughty/deobfuscate/templates/deobfuscate/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'deobfuscate/style.css' %}" />
    <title>JSNaughty - Deobfuscator for Javascript</title>
</head>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

jsnaughty/deobfuscate/templates/deobfuscate/get_js.html
{% extends "deobfuscate/new_base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- <div class="inline-div"> -->
<div class="col-md-6">
<h2> Input Minified Javascript: </h2>
<form action="{% url 'deobfuscate:get_js'  %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class = 'btn-primary pull-left' type="submit" value="Submit" />
&nbsp&nbsp<a href="https://github.com/bvasiles/jsNaughty/tree/master/DockerFolder#included-data-and-expected-run-times" style="display: inline;">Note: Processing may take a few seconds, please wait.</a>
</form>
</div>


<div class="col-md-6">
<h2>The Renamed Javascript: </h2>
<textarea class="inline-txtarea textarea form-control" cols="40" id="id_in_text" name="in_text" rows="10">
{{ out_text }}
</textarea>
</div>
{% endblock %}

jsnaughty/deobfuscate/templates/deobfuscate/index.html
{% extends "deobfuscate/new_base.html" %}
{% block content %}
<ul>
    <li><a href="{% url 'deobfuscate:get_js' %}"> Go to Javascript Deobfuscation Tool</a></li>
</ul>
{% endblock %}

jsnaughty/deobfuscate/templates/deobfuscate/minify.html
{% extends "deobfuscate/new_base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- <div class="inline-div"> -->
<div class="col-md-6">
<h2> Input Javascript here: </h2>
<form action="{% url 'deobfuscate:minify'  %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class = 'btn-primary pull-right' type="submit" value="Submit" />
</form>
</div>


<div class="col-md-6">
<h2>The Minified Javascript: </h2>
<textarea class="inline-txtarea textarea form-control" cols="40" id="id_in_text" name="in_text" rows="10">
{{ out_text }}
</textarea>
</div>
{% endblock %}

jsnaughty/deobfuscate/templates/deobfuscate/new_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JSNaughty - Deobfuscator for Javascript</title>

    <!-- Bootstrap Core CSS -->

    <link href="{% static 'deobfuscate/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">   


    <!-- Theme CSS (Store as min) -->
    <link href="{% static 'deobfuscate/css/clean-blog.css' %}" rel="stylesheet"> 

    <!-- Custom Fonts -->
    <link href="{% static 'deobfuscate/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Small Textarea tweak -->
    <link href="{% static 'deobfuscate/css/style.css' %}" rel="stylesheet"> 

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">{{ request.site.name }}</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                     <a href="{% url 'deobfuscate:get_js' %}">Home</a>
                    </li>
                    <li>
                    <a href="{% url 'deobfuscate:minify' %}">Minify</a>
                    </li>
                    <li>
                     <a href="{% url 'deobfuscate:team' %}">Team</a>
                    </li>
                    <li>
                    <a href="{% url 'deobfuscate:about' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'deobfuscate/img/topbar.jpg' %})">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>JSNaughty</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row">
            <!-- <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1"> -->
                {% block content %}{% endblock %}
            <!-- </div> -->
        </div>
    </div>


    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://github.com/bvasiles/jsNaughty">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; {{ request.site.name }} {% now "Y" %}</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'deobfuscate/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'deobfuscate/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'deobfuscate/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'deobfuscate/js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'deobfuscate/js/clean-blog.min.js' %}"></script>


</body>

</html>

jsnaughty/deobfuscate/templates/deobfuscate/results.html
{% extends "deobfuscate/base.html" %}

{% block content %}
<h2>Behold, The Deobfuscated Javascript: </h2>
<textarea rows = "{{ height }}" cols = "{{ width }}">
{{ out_text }}
</textarea>
{% endblock %}

jsnaughty/deobfuscate/templates/deobfuscate/team.html
{% extends "deobfuscate/new_base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>JSNaughty is being created and maintained by:</p>

<div><img src = "{% static 'deobfuscate/img/bogdan.jpg' %}" style="float:left;margin-right:20px" /></div>
<div style="vertical-align: middle;">
<a href="http://bvasiles.github.io">Bogdan Vasilescu</a>, 
Assistant Professor at <a href="http://www.cmu.edu">Carnegie Mellon University</a>
</div>
<div style="clear:left"><br /></div>
	    
<div><img src= "{% static 'deobfuscate/img/casey.jpg' %}" style="float:left;margin-right:20px" /></div>
<div style="vertical-align: middle;">
<a href="http://caseycas.github.io">Casey Casalnuovo</a>, 
Graduate Student at <a href="http://www.ucdavis.edu">UC Davis</a>
</div>
<div style="clear:left"><br /></div>

<div><img src= "{% static 'deobfuscate/img/prem.jpg' %}" style="float:left;margin-right:20px" /></div>
<div style="vertical-align: middle;">
<a href="http://web.cs.ucdavis.edu/~devanbu/">Prem Devanbu</a>, 
Professor at <a href="http://www.ucdavis.edu">UC Davis</a>
</div>
<div style="clear:left"><br /></div>


<h4 id="acknowledgment">Acknowledgments</h4>
<p>We gratefully acknowledge support from NSF <a href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=1414172&HistoricalAwards=false">1414172</a>,  SHF: Large: Collaborative Research: Exploiting the Naturalness of Software.</p>

    </div>
  </div>
</div>
{% endblock %}